### ISSUE TITLE
Issues authenticating locally

### ISSUE THREAD

**Issue by kmudrick** [whatadewitt/yahoofantasysandbox#3]
I created a new app here: https://developer.yahoo.com/apps/

I set my callback domain to 127.0.0.1 (yahoo considers localhost invalid)

![image](https://cloud.githubusercontent.com/assets/204913/20611895/7530f2c4-b280-11e6-92b5-2c444d87e1ff.png)

I copied `conf.sample.js` to `conf.js` and dropped in my key and secret and set my app url to `http://127.0.0.1:9999`

Started the app with `PORT=9999 npm start`

When I click login, I see the following.

![image](https://cloud.githubusercontent.com/assets/204913/20611883/479ca02e-b280-11e6-91c3-b24214f04941.png)

Does anything else need to be done differently to get this to work locally?

**Comment by whatadewitt** [comment]
I have never had luck getting it to work on a port other than 80... I also set up an entry in my hosts file as it didn't like localhost...

**Comment by kmudrick** [comment]
Ahh, thanks @whatadewitt - 80 does indeed work fine :)
