### ISSUE TITLE
How to use on localhost

### ISSUE THREAD

**Issue by gummie4444** [whatadewitt/yahoofantasysandbox#4]
Can't get it to work on localhost/127.0.0.1 after i click login it always return's (whatever port)

"               Uh oh
Looks like something went wrong.
Please try again later."

-I've both used installed application/web application both does not work
-It work's for online websites : http://example.com
-used multiple oauth2 libaries (oauth2,yahoostrategy)
-used normal request does not work then
-used different ports
-can not add the redirect url's to dev.yahoo.com/apps returns: " Application Create failed. Scopes creation failed when creating App: 507 - {"domain_name":{"errors":[{"code":2402,"message":"Invalid domain name: 127.0.0.1:3000"}]}}"

redirect url is either http://localhost:****/auth/callback or http://127.0.0.1:****/auth/callback

What are you doing to make local dev work:S?

**Comment by whatadewitt** [comment]
I've had a lot of issues getting it to run on a non-standard port.

I set up the server to run on port 80 and then also created an entry in my hosts file that I entered into Yahoo!

Hope this helps!

**Comment by gummie4444** [comment]
Yehh I tried to use port 80 and got in troubles doing that but found a solution using nginx and port 80.

For mac:
1. Insert nginx
`brew install nginx`
2. Configure nginx to reroute to a custom url
`sudo nano /usr/local/etc/nginx/nginx.conf`
Find the server section and change the configuration to this
 ```
server {
    listen       80;
    ...
    location / {
        proxy_pass http://127.0.0.1:****(your port);
    }
    ...
}
 ```

3. Configure your host file to reroute localhost/127.0.0.1 to a custom url
`sudo nano /etc/hosts`
Add the entry for example mywebsite.dev
`127.0.0.1 mywebsite.dev`
4. Run nginx and run the server
`sudo nginx   sudo app.js`
5. Insert on yahoo.developer in the callback URL mywebsite.dev

**Comment by whatadewitt** [comment]
Glad you were able to find a solution :)
